import "dotenv/config"; import express from "express"; import { z } from "zod";
const app = express(); app.use(express.json({ limit: "100kb" }));
const catalog = [{ name: "get_event_guidance", description: "Read official organizer-backed guidance, tracks, deliverables and sponsor criteria.", inputSchema: { type: "object", properties: { question: { type: "string" } }, required: ["question"], additionalProperties: false } }, { name: "validate_project_strategy", description: "Use premium organizer intelligence to validate a project strategy.", inputSchema: { type: "object", properties: { idea: { type: "string" }, track: { type: "string" } }, required: ["idea"], additionalProperties: false } }, { name: "audit_submission", description: "Run a premium audit for requirements, evidence and blockers.", inputSchema: { type: "object", properties: { repositoryUrl: { type: "string", format: "uri" }, summary: { type: "string" } }, required: ["summary"], additionalProperties: false } }] as const;
const argumentsSchemas = { get_event_guidance: z.object({ question: z.string().min(1).max(2000) }).strict(), validate_project_strategy: z.object({ idea: z.string().min(1).max(5000), track: z.string().min(1).max(200).optional() }).strict(), audit_submission: z.object({ repositoryUrl: z.string().url().optional(), summary: z.string().min(1).max(5000) }).strict() } as const;
const request = z.object({ method: z.string(), params: z.record(z.unknown()).optional(), id: z.union([z.string(), z.number()]).optional() }); const reply = (id: unknown, result: unknown) => ({ jsonrpc: "2.0", id: id ?? null, result }); const error = (id: unknown, message: string, data?: unknown) => ({ jsonrpc: "2.0", id: id ?? null, error: { code: -32602, message, data } });
app.get("/health", (_q, r) => r.json({ ok: true, service: "hackrails-mcp", tools: catalog.map(t => t.name) }));
app.post("/mcp", async (q, r) => { const parsed = request.safeParse(q.body); if (!parsed.success) return r.status(400).json(error(null, "Invalid JSON-RPC request", parsed.error.flatten())); const { method, params = {}, id } = parsed.data; if (method === "initialize") return r.json(reply(id, { protocolVersion: "2024-11-05", serverInfo: { name: "hackrails-mcp", version: "0.1.0" }, capabilities: { tools: {} } })); if (method === "tools/list") return r.json(reply(id, { tools: catalog })); if (method !== "tools/call") return r.status(404).json(error(id, "Method not found")); const name = params.name; if (typeof name !== "string" || !(name in argumentsSchemas)) return r.status(400).json(error(id, "Unknown tool")); const args = argumentsSchemas[name as keyof typeof argumentsSchemas].safeParse(params.arguments ?? {}); if (!args.success) return r.status(400).json(error(id, "Invalid tool arguments", args.error.flatten())); const auth = q.header("authorization"); if (!auth?.startsWith("Bearer ")) return r.status(401).json(error(id, "Authorization bearer token required")); try { const api = await fetch(`${process.env.API_URL ?? "http://localhost:4000"}/internal/mcp/call`, { method: "POST", headers: { "content-type": "application/json", authorization: auth, "idempotency-key": q.header("idempotency-key") ?? crypto.randomUUID() }, body: JSON.stringify({ tool: name, payload: args.data }) }); const body = await api.json(); if (!api.ok) return r.status(api.status).json(error(id, body.error ?? "Tool request rejected", body.details)); return r.json(reply(id, { content: [{ type: "text", text: JSON.stringify(body, null, 2) }], structuredContent: body })); } catch (e) { return r.status(502).json(error(id, (e as Error).message)); } });
app.listen(Number(process.env.PORT ?? 4001), () => console.log("HackRails MCP listening"));
export { argumentsSchemas };
